#!/usr/bin/env bash
#Display 'Best school' to the standard outupt until a condition

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo 'Hi'
	fi
	echo 'Best School'
	((index++))
done
