#!/usr/bin/env bash
#Loops from 1 to 10 

index=0

while [ $index -lt 0 ]
do
	if [ $index -eq 3 ]
	then
		echo 'bad luck'
	elif [ $index -eq 7 ]
	then
		echo 'good luck'
	fi
	echo 'Best School'
	(( index++ ))
done
