#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
